version: '3.7'

services:
  users-db:
    build:
      context: ./users-service-flask/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  users:
    build:
      context: ./users-service-flask/users
      dockerfile: Dockerfile
    volumes:
      - './users-service-flask/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig 
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db

  orders:
    build:
      context: ./orders-service-flask/orders
      dockerfile: Dockerfile
    volumes:
      - './orders-service-flask/orders:/app'
    ports:
      - 5002:80

  client:
    build:
      context: ./front-service-vue
      target: 'develop-stage'
    ports:
      - 8080:8080
    volumes:
      - './front-service-vue:/app'
    environment:
      - VUE_APP_USERS_SERVICE_URL=http://localhost:5001
      - VUE_APP_ORDERS_SERVICE_URL=http://localhost:5002
    command: /bin/sh -c "npm run serve"
    depends_on:
      - users
      - users-db
      - orders
